spring.application.name=Gateway-Service3

server.port=8080


spring.config.import=optional:configserver:http://localhost:8888

#management.endpoints.web.exposure.include=*
#management.endpoint.gateway.access=unrestricted
