
#Application
spring.application.name=User-Service1
server.port=8081

#Config Service
spring.config.import=optional:configserver:http://localhost:8888

#PostgreSQL DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=Shaikali@270
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect